### ISSUE TITLE
Scanner results

### ISSUE THREAD

**Issue by rimvislt** [OWASP/ASST#1]
After running scanner found few reported issues:

1) Most are related to vendor folder - should it do scanning on it?
vendor/twig/twig/composer.json Weird file found in your project!, make sure it belongs there, if it doesn't, remove it. (here is 1 example where it is)
+ (examples inside some of 3rd party packages reported as errors) 

2)  public/robots.txt Weird file found in your project!, make sure it belongs there, if it doesn't, remove it. (this is correct file used for crawlers - bots)

* Trying to figure out how to use this scanner with docker where api is running via 2 containers:   php-container + nginx container. Can you suggest some ways how to use it on jenkins while building containers or to run it on AWS ECS/EKS ?

**Comment by rimvislt** [comment]
other issue:
".htaccess file couldn't be detected, .htaccess file must exists in the project's root folder and have rules to prevent directory listing (index)."  - nginx does not support htaccess files :)

**Comment by TarikSeyceri** [comment]
You are right, most these detections are false positives, you can simply ignore them for now, hopefully i will have time to fix them.

You are welcome to help in suggesting updates and fixes to it.

Running this tool is just like running a node.js application, so if jenkins, docker or any container supports node.js, then you are good to go.

Good luck.

**Comment by rimvislt** [comment]
Thanks I will send few PRs for it once get hands on fixing it for linux :)
