### ISSUE TITLE
project_database.sql

### ISSUE THREAD

**Issue by meetgyn** [OWASP/ASST#2]
I did not find the database to import. I created an empty bank, but where is SQL for me to do the import? This part I did not understand 
import your project_database.sql

**Comment by TarikSeyceri** [comment]
This tool is a Source Code scanning tool, it does not have an SQL file for it to operate, the part where it says "import your project_database.sql" is for the project's database that you want to scan, it is not the tool's database sql file, if the project that you want to scan doesn't have DBMS (MySQL), you can simply disable the scanning feature for it in "config_php_lang.js" file by setting "IS_DBMS_USED" attribute to false.
