### ISSUE TITLE
MySQL server version check is not updated for 8.0

### ISSUE THREAD

**Issue by lunzai** [OWASP/ASST#3]
`if(core.replaceAll(mysqlVersion.toString(), ",", "") < 100408){`

Right now it's checking for innodb_version >= 10.04.08, however, as of MySQL 8.0, innodb_version return version number of the server, which will fail this MySQL version check.

> innodb_version
> 
> The InnoDB version number. In MySQL 8.0, separate version numbering for InnoDB does not apply and this value is the same the version number of the server.

https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_version

**Comment by TarikSeyceri** [comment]
Can you please suggest a fix (PR), it is been more than one year, i will have to reread the code and check it, and currently i am so overwhelmed and busy, Thank you..
