### ISSUE TITLE
Install Mathjs

### ISSUE THREAD

**Issue by ainnamran20** [OWASP/ASST#4]
Hi and good day,

I would like to ask, why the error kept on showing as i already tried to installed 3 different version of node.js (v12, v20, and v21) but the error kept on showing the same things. Do you have any suggestion for this?

![image](https://github.com/OWASP/ASST/assets/108723258/e1fc345b-b0f6-4e3f-9a0e-66cd03bca66f)

**Comment by TarikSeyceri** [comment]
For some reason it happened in your environment, but i made sure it won't happen again.

Thank you for reporting.
