### ISSUE TITLE
MODULE NOT FOUND ERROR IN LARAGON (ALTERNATIVE OF XAMPP)

### ISSUE THREAD

**Issue by chiragparmar-kombee** [OWASP/ASST#5]
Hi There,

I am currently using Laragon instead of XAMPP and attempting to integrate the ASST package for the SAST (Static Application Security Testing) approach. However, I am encountering the following error:

Could you kindly assist in identifying if I might be missing any steps or configuration? Your guidance would be greatly appreciated.

Thank you for your time and support.

![image](https://github.com/user-attachments/assets/4c27d421-7550-4dd3-8a68-05ef8e09330e)

**Comment by TarikSeyceri** [comment]
Hi, 

Did you run the following command?:

npm install

**Comment by chiragparmar-kombee** [comment]
Thank you after run _npm install_ command it is working.
